//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.02 at 05:08:30 PM PDT 
//


package com.inktomi.cirrus.nws.forecast;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;

import java.util.Date;
import java.util.List;

@Element
public class TimeLayout {

    @Element(type = String.class, name = "layout-key", required = true)
    public String layoutKey;

    @ElementList(type = Date.class, entry = "start-valid-time", required = false, inline = true)
    public List<Date> startValidTime;

    @ElementList(type = Date.class, entry = "end-valid-time", required = false, inline = true)
    public List<Date> endValidTime;

    @Attribute(name = "time-coordinate", required = true)
    public TimeCoordinate timeCoordinate;

    @Attribute(name = "summarization", required = false)
    public String summarization;
}
